language: bash

before_script:
    - wget -O "/tmp/xerces.tar.gz" "http://apache.openmirror.de/xerces/j/binaries/Xerces-J-bin.2.11.0.tar.gz" 
    - tar xvzf /tmp/xerces.tar.gz

script:
    - bash test/validate.sh -v -n -np -s -f ows/wfs/1.1.0/weichand/request/GetFeature_by_BoundingBox.xml
